### ISSUE TITLE
Seem to be crashing when involved with parties.

### ISSUE THREAD

**Issue by Malax123** [EpsilonWoW/Enteleaie#12]
Crashed twice whilst within a party, the error report seems to suggest it's involved with being in a party, don't know if it's my client or server side: 

This application has encountered a critical error:

Not enough storage is available to process this command.

Program:	C:\Users\Elliot\Desktop\World of Warcraft - Divinity-X Client\World of Warcraft - Divinity-X Client\WoW.exe
Object:	PartyMemberAuraStates (.?AUPartyMemberAuraStates@@)

Requested 83886240 bytes of memory

WoWBuild: 13623
Realm: EpsilonWoW [play.epsilonwow.net:8085]
Local Zone: Trade District, Stormwind City
Local Player: Malax, 0000000000000004, (-8835.05,626.389,94.1133)
Current Object Track: Trias' Cheese, F1100301FE0294B5, (-8859.88,584.693,97.7821)
Total lua memory: 13311KB
Current Addon: (null)
Current Addon function: UNKNOWN
Current Addon object: (null)
Settings: 
SET locale "enGB"
SET enterWorld "1"
SET realmList "play.epsilonwow.net"
SET hwDetect "0"
SET gxWindow "1"
SET gxResolution "1920x1080"
SET gxRefresh "60"
SET gxMultisampleQuality "0.000000"
SET gxFixLag "0"
SET videoOptionsVersion "4"
SET graphicsQuality "5"
SET textureFilteringMode "5"
SET playIntroMovie "4"
SET Gamma "1.000000"
SET readTOS "1"
SET readEULA "1"
SET readTerminationWithoutNotice "1"
SET showToolsUI "1"
SET accounttype "CL"
SET Sound_EnableAllSound "0"
SET Sound_MusicVolume "0.40000000596046"
SET Sound_AmbienceVolume "0.60000002384186"
SET componentTextureLevel "9"
SET terrainMipLevel "0"
SET farclip "1250"
SET waterDetail "3"
SET sunShafts "2"
SET groundEffectDensity "128"
SET groundEffectDist "260"
SET environmentDetail "150"
SET projectedTextures "1"
SET shadowMode "3"
SET shadowTextureSize "2048"
SET weatherDensity "3"
SET realmName "EpsilonWoW"
SET gameTip "17"
SET mouseSpeed "1"

**Comment by timgblack** [comment]
This seems to have to do with party auras, like the ones found on Paladins, Warriors or Hunters.

**Comment by timgblack** [comment]
We now can't recreate this. I'll look into it in the open beta if it rears it's head again.

**Comment by timgblack** [comment]
I believe I have fixed this, however it requires more testing before I'll sign it off as complete.

**Comment by Malax123** [comment]
Invited David into a group, seems to be no issues. Moved to a different map, no issue. Went into a different phase, no issue. Seems no be having no issues at all.

**Comment by Malax123** [comment]
As soon as David logged back into the server, whilst still in the party, I suffered the same error.

**Comment by timgblack** [comment]
The client crash is irrelevant and uninteresting (... in the context of this issue, anyway). I'm interested in whether you can log into the server without it crashing while in a party as leader or otherwise.

**Comment by timgblack** [comment]
Whoops, wrong bug.

**Comment by timgblack** [comment]
This is not fixed and I have no plans to try and fix it; deal with it.
