### ISSUE TITLE
.mod scale

### ISSUE THREAD

**Issue by Malax123** [EpsilonWoW/Enteleaie#13]
Attempted to enter the command .mod scale; typed, ".mod scale 1.3". Server crashed straight afterwards, only other person online at the time was Aaron, but he said he wasn't doing anything.

**Comment by EpsilonGrimm** [comment]
Update: May be an issue with permission checking. Command works for Everon, but crashes for myself and Malax.

**Comment by timgblack** [comment]
I'm looking into this.

**Comment by ever0n** [comment]
Command fixed in commit 14ec056. Tested with full donor permissions.
