### ISSUE TITLE
Native displayID error.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#18]
If I use nativedisplayid and run through hairstyles as another race, some hairstyles will cause an error. I suppose this could just be a common sense thing, but I thought I'd raise the issue anyway.

**Comment by timgblack** [comment]
What error?

**Comment by ever0n** [comment]
@Aarontravess please update with error.

**Comment by timgblack** [comment]
I don't think it's realistic to expect that nativedisplayids will work with this. While I'd love for it to work, it's simply taking the features of one race and loading them from another race - unless there's no overlap anywhere (which is a client side), this is always going to be a problem.
