### ISSUE TITLE
phase setmessage \

### ISSUE THREAD

**Issue by MindScape00** [EpsilonWoW/Enteleaie#19]
Certain characters in the command will consistently, within ".phase setmessage", give an extra "\". Not a huge problem, but still annoying.

https://i.imgur.com/70c549J.png

**Comment by timgblack** [comment]
It looks like it's not being properly escaped when it's being retrieved from the database. I'll look into it.

**Comment by timgblack** [comment]
It's being retrieved fine (confirmed 2015-06-18 3:22PM GMT):
You have joined phase Winter Storm [17].
[17]: Testing ------    '  \ "

So it's only a problem when setting it before a crash, which has been fixed.
