### ISSUE TITLE
Phase setweather unresponsive

### ISSUE THREAD

**Issue by Melarith** [EpsilonWoW/Enteleaie#20]
When setting your weather (i.e. to rain) in your phase and entering an interior, all weather effects disappear as intended. However, when leaving the interior there is a significant delay (20-60sec) before they return. All weather effects also disappear entirely and then reappear with a similar delay any time the player transitions from an area (Goldshire - Stormwind, Goldshire - Elwynn, Elwynn - Duskwood).

**Comment by timgblack** [comment]
This is (I think) the normal behaviour of weather anyway. There's not much can be done about it either way at this stage.
