### ISSUE TITLE
.go scale isn't saving.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#23]
Object scales reset after a disconnection.

**Comment by timgblack** [comment]
This will be fixed in the next version... which, as I didn't push my changes to the server, might be a few days. I'll try to get them pushed tonight so I can compile it tomorrow.

**Comment by timgblack** [comment]
I'll continue to look into this through the early stages of the OBT.

**Comment by timgblack** [comment]
I'm very glad to say that this has been fixed.
