### ISSUE TITLE
Guilds not being saved

### ISSUE THREAD

**Issue by Malax123** [EpsilonWoW/Enteleaie#25]
I made a guild for a Character (Malax), to add all the testers into it, I logged off the Character afterwards and the guild's not showing up anymore; however my Character's now not showing having a guild nor can I type in the /guild channel. When I go to delete the Character it tells me that the Character is a Guild Master.

**Comment by ever0n** [comment]
Needs to be confirmed.

**Comment by timgblack** [comment]
Looks like guilds DO save but may not load properly for all characters. I'll continue to look into this.

**Comment by DavidTwo** [comment]
aye i can confirm this. made a guild earlier <Kingdom of Leogard> and im suddenly not in it, but when trying to re-create said guild, it said the guild already exists.

**Comment by timgblack** [comment]
I'm looking into this bug, it should be resolved in the early stages of the OBT.

**Comment by timgblack** [comment]
The bug should be resolved in the next version.
