### ISSUE TITLE
Staff can spawn in the main phase but not select or delete.

### ISSUE THREAD

**Issue by ever0n** [EpsilonWoW/Enteleaie#26]
When trying to select an object spawned in the main phase you get the error message "You are in an invalid phase"

**Comment by ever0n** [comment]
else if (!ph || ph->GetPhaseID() > 4000000)
    {
        SystemMessageError(m_session, "You are in an invalid phase.");
    }

This snippet of code seems to be the issue.

**Comment by timgblack** [comment]
This should be fixed in the next version.
