### ISSUE TITLE
".go move"

### ISSUE THREAD

**Issue by MindScape00** [EpsilonWoW/Enteleaie#28]
Move your selected game object. Multiple implementation ideas:
1) ".go move" moves it to your current locations.
2) ".go move <X> <Y> <Z>" moves it relative to it's current position by given values.
3) ".go move <X> <Y> <Z>" moves it definitely to those given coordinates.

**Comment by timgblack** [comment]
I'm proposing that it moves the currently selected object to your location without arguments and to the specified coordinates with arguments. An optional orientation would be viable as well.

**Comment by timgblack** [comment]
The command is working so far, however it is only working on objects that were spawned and not loaded from the database. Why this is the case, I don't know.

I can add in checks for that so it fails on older objects (making the command useful only for newly spawned stuff), but I'll look into making it work for all objects before I go with that route.

**Comment by timgblack** [comment]
Because of the work required to get this working consistently and the lack of time I have to work on it, I am postponing work on (and release of) !gobject move for the time being. It will be finished after we go live.

**Comment by timgblack** [comment]
Due to recent changes, this is working better, however there are still issues with the rotation of the object not changing on move.
