### ISSUE TITLE
.mod displayid2 / .mod displayid perms not available. 

### ISSUE THREAD

**Issue by EpsilonGrimm** [EpsilonWoW/Enteleaie#29]
Donors do not have access to these commands.

**Comment by ever0n** [comment]
Displayid2 is no longer a command, it has been merged into .mod displayid, I believe that you need to vote to gain access to it. Permissions have been updated so this needs to be tested again.

**Comment by EpsilonGrimm** [comment]
Fixed, I was using displayid2 and displayid wasn't working because I hadn't relogged.
