### ISSUE TITLE
.acc mute

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#34]
.acc mute GRIMM 1h TEST

Made the server disconnect.

**Comment by Aarontravess** [comment]
Also worth noting that the mute didn't actually work, either.

**Comment by timgblack** [comment]
Turns out the table is missing, hah. But that means this is part of the database refactor which will take place over next month.

**Comment by timgblack** [comment]
I've fast tracked !account ban, !account mute and !ip ban for before open testing. These commands work as of open beta; another ticket will be created to track the other exile commands for early open beta.

!account ban, !account mute and !ip ban all work as expected.
