### ISSUE TITLE
.ticket close

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#36]
.ticket close causes a disconnection, either using the ticket ID or the character name.

**Comment by timgblack** [comment]
This should be fixed in the next version.

**Comment by EpsilonGrimm** [comment]
Appears to be fully functional in the latest version.

**Comment by Aarontravess** [comment]
.ticket close still causes a disconnection.

**Comment by timgblack** [comment]
I need more details. What did you type? What ticket were you trying to delete?

Especially, can this be performed again at some point?

**Comment by timgblack** [comment]
We've tried this again and it works. Schedule a time with me to break it, otherwise it's fixed.
