### ISSUE TITLE
Exile commands

### ISSUE THREAD

**Issue by timgblack** [EpsilonWoW/Enteleaie#42]
!account ban, !account mute and !ip ban are working.
!account unban, !account unmute, !ip unban, !ip mute and !ip unmute are not.

**Comment by timgblack** [comment]
This is an early part of #2.

**Comment by ever0n** [comment]
@timgblack There's an issue with !account ban, if you look at the DB table it is storing the account name under the reason field and 0 under the banned by field.

**Comment by ever0n** [comment]
Same as above also applies for !ip ban.
