### ISSUE TITLE
Phase owners cannot scale objects in their own phase

### ISSUE THREAD

**Issue by AddieA** [EpsilonWoW/Enteleaie#43]
Objects can be selected but the following error appears when using the !go scale command:

"Your privileges are insufficient to scale gameobjects in this phase."

**Comment by AddieA** [comment]
Correction: This only happens if the objects belong to a ported phase - Phase 13 was ported and the owner does not seem to be able to scale the objects. Tried to recreate the issue by making a new phase - phase ID 28 - and objects appear to scale without any issue.

**Comment by AddieA** [comment]
Correction 2: Before the server restart, the objects I spawned in my own phase could scale without a problem. Their owner was my account ID. After the crash, I can no longer scale the objects and their owner was changed to 0.

**Comment by timgblack** [comment]
The issue where officers of a phase could not scale objects which did not belong to them should be fixed in the next version.
