### ISSUE TITLE
Unsaved objects remain after a restart 

### ISSUE THREAD

**Issue by AddieA** [EpsilonWoW/Enteleaie#44]
I spawned 2 objects in my phase, different types, and did not add a "1" at the end, in order to save them. After a restart, they remained in my phase.

**Comment by timgblack** [comment]
This is because we currently aren't running GUID maintenance. I'll make sure this runs at least once every three days or so.

**Comment by timgblack** [comment]
Nevermind; it already runs every three days. GUID maintenance deletes all temporary (unsaved) objects as well as compacting all object and NPC guids.
