### ISSUE TITLE
Object scale.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#49]
Objects are shown as scale 1 in the database, but spawn ingame as size 0.000.

Spawned gameobject entry 4035811 name World\Expansion05\Doodads\Draenei\6dr_draenei_karabor_bigdoor.mdx, id 240514 at co-ordinates XYZ -7749.004395 1084.083740 131.407120.

You have selected gameobject [World\Expansion05\Doodads\Draenei\6dr_draenei_karabor_bigdoor.mdx] with id 240514, entry 4035811 at co-ordinates XYZ -7749.004395 1084.083740 131.407120 on map 723 facing 1.725368 which is 0.000000 meters away from you. Owner is account id 12.

Gameobject Info:
GUID: 240514
Entry: 4035811
Name: World\Expansion05\Doodads\Draenei\6dr_draenei_karabor_bigdoor.mdx
Scale: 0.000000
Distance: 0.832520
Owner: 12

![size](https://cloud.githubusercontent.com/assets/12838807/8593373/1566c154-262f-11e5-8f97-3ac238edeae4.png)

**Comment by DavidTwo** [comment]
Yeah, I encountered this bug too after one of the recent builds he made to try and fix .go delete. When I was spawning barber chairs earlier, the default scale on them was 0 instead of 1 (as it should be).

**Comment by timgblack** [comment]
I can do one of two things:
Spawn objects at scale 1 (regardless of database scale)
Use the database scale

**Comment by timgblack** [comment]
Objects will, when spawned, use their template scale unless they have another scale set.

A side effect of this is that objects with a negative scale will revert to their database scale on a server restart. If this side effect is a problem in the future, open a new ticket about it.
