### ISSUE TITLE
New WoD Objects from 4035056 - 4040512 don't save.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#51]
Title is self explanatory. I spawned a load of the new objects, saved some of them. After a disconnection, which I caused deliberately using .ticket close, I came back and they were -all- gone.

**Comment by timgblack** [comment]
They probably aren't in the server DBCs. Send me an updated one and I'll add it in.

**Comment by timgblack** [comment]
This was resolved with updated DBC files.
