### ISSUE TITLE
Newly registered accounts do not have permissions

### ISSUE THREAD

**Issue by DavidTwo** [EpsilonWoW/Enteleaie#52]
Title elaborates it. Someone told me that when they registered for the Open Beta, that they had no access to any commands. And I registered a test account to check, and I too, cannot use commands on this freshly registered account (My other account is fine, however).

Almost as if newly registered accounts have the "0" permission set, or even none at all.

EDIT: Decided to .player that test account I made, and these were the results:
Davidtest connected through account 'DAVIDTWO' [81] with permissions ''

So no permissions attached to the newly registered account.

**Comment by timgblack** [comment]
This is known and going to be fixed soon.

**Comment by ever0n** [comment]
Fixed.
