### ISSUE TITLE
!phase announce duplicating when there is more than one person in the phase

### ISSUE THREAD

**Issue by DavidTwo** [EpsilonWoW/Enteleaie#53]
I'm a bit skeptical of this one. I noticed it last time, but it went away after a few messages. But while fooling with .ph ann with Grimm in my phase, I noticed .ph ann was duplicating when I typed in it. And I also couldn't see what he was saying in .ph ann. When Grimm left my phase, .ph ann only showed one message when i typed in it. when i entered phase 13 earlier and tested .ph ann, no duplication was happening. But when I joined it when Grimm was in it and tested .ph ann, it was duplicating again
http://i.imgur.com/kKWsOgm.jpg
http://i.imgur.com/l53iRrb.jpg
(Reference images)

**Comment by timgblack** [comment]
This should be fixed in the next version.
