### ISSUE TITLE
List of spells that should get disabled! (Will be constantly updated as I find them)

### ISSUE THREAD

**Issue by Chedders** [EpsilonWoW/Enteleaie#55]
Hello! Chada here to tell you a nice list of growing spells that should get disabled as they can be very annoying/abusive. Will update as time goes on!

Charm - Spell ID 530
Frost Bomb - Spell ID 70521
Tentacle Knockback (h) - Spell ID 80241
Tentacle knockback HORDE - Spell ID 80267
Knock away - Spell ID 64022
Knock Away - Spell ID 37102
Mirror Image Base Spell. Makes people the same name as the original caster.

**Comment by timgblack** [comment]
Please only edit until I've given said that the current spells have been restricted, then make a new comment so I know what is new. Thanks! (Keep editing as of this comment, though).
