### ISSUE TITLE
[Spell List Feature(?)] Passive Marker

### ISSUE THREAD

**Issue by Kalrihk** [EpsilonWoW/Enteleaie#69]
When you look up spells, you can't exactly figure out whether if it is a castable or a passive, until you click on it, or even experiment with it if you have to.

Perhaps add a feature that may show 'PASSIVE' in some stand-out text to the right of each spell that shows up in the list?

**Comment by timgblack** [comment]
This was a simple change, so it'll be pushed with another update.
