### ISSUE TITLE
Expansions need to be enabled.

### ISSUE THREAD

**Issue by Aarontravess** [EpsilonWoW/Enteleaie#8]
Self explanatory, can't make races or classes from any of the expansions.

**Comment by ever0n** [comment]
Updated account table to enable expansion access for all current accounts, future accounts should have it by defauly.

**Comment by ever0n** [comment]
Accounts are set correctly in the DB and in worldserver.conf however expansions are still disabled.

**Comment by timgblack** [comment]
This has been fixed. The DB expansion is now irrelevant.
